    //Declaração da classe Monitor
public class Monitor {
	//Características
    public String cor;
	public String marca;
	public String modelo;
    public Double tamanho;
    public Double peso;	
	/*
    
  // Métodos para mudar o monitor
  public void mudar (String numeroMonitor) {
	  System.debug ('Mudando do monitor: '
                 + numeroMonitor
                 + '\n para :	' + monitor
                 + '\n Marca/Modelo : '
                 + marca	+ '/' + modelo);						
  }
  public void	exibirMensagem (String mensagem) {
	  System.debug('[' + monitor + ']\n'
                + 'Mensagem: ' + mensagem);					
  }   */     
}

